trigger:
  branches:
    include:
      - refs/heads/main
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: ubuntu-18.04
    steps:
      - checkout: self
      - task: Docker@0
        displayName: Build Container
        inputs:
          containerregistrytype: Container Registry
          imageName: landing-page-$(Build.SourceVersion)-$(Build.BuildId)
          additionalImageTags: $(Build.SourceVersion)-$(Build.BuildId)
          includeSourceTags: true
          includeLatestTag: true
      - task: ECRPushImage@1
        displayName: Push Image to ECR
        inputs:
          awsCredentials: 63e72a12-b8c8-4c47-92fd-1d7d3108e349
          regionName: us-east-1
          sourceImageName: landing-page-$(Build.SourceVersion)-$(Build.BuildId)
          repositoryName: bylines/landing-page
      - task: AWSCLI@1
        displayName: Update ECS Service
        inputs:
          awsCredentials: 63e72a12-b8c8-4c47-92fd-1d7d3108e349
          regionName: us-east-1
          awsCommand: ecs
          awsSubCommand: update-service
          awsArguments: --cluster bylines-landing-page --service bylines-landing-page --force-new-deployment
          failOnStandardError: false